spring.application.name=bank

# DB Connection
spring.datasource.url=jdbc:mysql://localhost:3306/db_crime?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Shun19004mathi@

# Hibernate Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl_auto=update